### ISSUE TITLE
Expand Parenthetical Content in Remove Parenthesis

### ISSUE THREAD

**Issue by HarryBaker** [NIHOPA/NLPre#10]
Parenthetical content is now expanded rather than deleted. That is, "ABC(DE(FG)H)I" is now processed as "ABCI.DEH.FG". However, the parser will still split all sentances on periods, regardless of whether these periods are in parenthetical content. That is, "AB(CD.EF)G" is processed as "AB(CD.EF)G" -> "ABCD.EFG". It should instead be processed as "ABG.CD.EF"

**Comment by thoppe** [comment]
I'm tagging this as a known issue that we can come back to later.
