### ISSUE TITLE
Performance: separate_reference is orders of magnitude slower than the other preprocessors

### ISSUE THREAD

**Issue by ldorigo** [NIHOPA/NLPre#113]
Hi there,

I don't have time to look in the details of why, but some profiling of my code shows that the preprocessor `separate_reference` is extremely slow compared to the other components.

It takes approx. 1 second per pubmed abstract to run - the next slowest one ran in ~0.05 seconds.

Let me know if you need more information.

**Comment by thoppe** [comment]
Thanks for the information. We are unable to reproduce this exactly. `separate_reference` is indeed slow, but not slower than the replacement of the acronyms. See this chart here for local timing tests:

https://github.com/NIHOPA/NLPre/tree/master/development

If you figure out a way to speed it up (and still pass all the unit tests!) let us know!
