### ISSUE TITLE
Doc strings

### ISSUE THREAD

**Issue by thoppe** [NIHOPA/NLPre#25]
All classes should have a valid (and useful!) docstring. See 

http://stackoverflow.com/a/24385103/249341

for some good examples. The "google" format is a good one to template.

**Comment by HarryBaker** [comment]
When writing the doc string, should I write docstrings for the individual functions within each class as well? Pretty much all of the classes are called, where the input and output are described. That's how I described most of the classes in their docstring. Should I write that as the docstring for the call function, and then provide a more general overview of the class in it's class-specific docstring, or is that overkill?

**Comment by thoppe** [comment]
Not overkill. Technically `__init__` and `__call__` are different (though in most cases `__init__` is empty). The description of the function should be in `__init__` along with any input parameters (like the one for replace dict), and the call function should describe the outputs specifically. As an example look at sklearn does it:

http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html

All functions get called with `.fit()` but init is important in a different way.
