### ISSUE TITLE
Clearer File Titles

### ISSUE THREAD

**Issue by HarryBaker** [NIHOPA/NLPre#27]
"remove_parenthesis.py" isn't an accurate description of what this module now does, since it now expands parenthetical content rather than delete it. Does "expand_parenthetical_content.py" work as a name?

Similarly, I'd like to rename "replace_from_dict.py" to "replace_from_mesh_dict.py"

These changes need to be reflected in the init file and the README--is there anywhere else they need to be reflected?

**Comment by thoppe** [comment]
Only in the `__init__.py` and the imports used in test. Otherwise go for it.

**Comment by thoppe** [comment]
To keep it generic and clean, let's keep replace: though I renamed it `replace_from_dict` to `replace_from_dictionary`. In theory, it should handle any dictionary file. As for remove_parenthesis, that can still be changed.
