### ISSUE TITLE
Periods Appended in Parenthetical Content

### ISSUE THREAD

**Issue by HarryBaker** [NIHOPA/NLPre#28]
Should we add periods to the end of parenthetical sentence content? Ie, do we want "Hello (hello world1) world2. Hello world3." -> "Hello world2 .\nHello world1 .\nHello world3." ? Currently parenthetical content has the newline appended correctly, but we don't manual append a period. It seems like we should if these modules are meant to be modular.

**Comment by thoppe** [comment]
We should not add characters that were not in the original text (with the exception of whitespace), unless the function is clear that it is doing some replacement (like replace from dict).

**Comment by HarryBaker** [comment]
We might need to manual append periods to parenthetical content. sentence_tokenizer (which uses pattern.en.parse) splits sentences on periods, and does not split them on newline characters. This results in parenthetical sentence being pre-pended to whatever sentence comes next.

**Comment by thoppe** [comment]
Hmmmm, good point. This is why we need the full linked tests! I agree with you, add a period for those missing it after then parenthetical.
