### ISSUE TITLE
Titlecaps converts to unicode

### ISSUE THREAD

**Issue by HarryBaker** [NIHOPA/NLPre#30]
the titlecaps class calls sentence_tokenizer from tokenizers.py to split the string into sentances. However, sentence tokenizer returns the sentences as unicode strings, which breaks other modules downstream. Should I re-run unidecoder after titlecaps, or edit sentence_tokenizer?

**Comment by HarryBaker** [comment]
Ok, while it doesn't actually break the downstream modules (they were breaking because I ran the phrase identifier after the mesh term replacement, titlecaps still converts to unicode. Is this a problem?

**Comment by thoppe** [comment]
I'm not sure it will be a problem, and it will be one that will go away on python 3. However, if it doesn't directly break anything (and if it does reopen this with a minimal working example), it's fine to leave it for now.
