### ISSUE TITLE
Single sentences in parenthesis bug

### ISSUE THREAD

**Issue by HarryBaker** [NIHOPA/NLPre#33]
Just noticed this as I was leaving. If a single sentence is put in parenthesis, the parenthesis are not being deleted properly. For instance, "Hello world. (It is a beautiful day.) Goodbye world" is split into three sentences: 'Hello world.' , '(It is a beautiful day.)', 'Goodbye world'.

I would expect it to split into: 'Hello world.', (It is a beautiful day.' , ') Goodbye world' . I'm not sure why it's not.

**Comment by HarryBaker** [comment]
I added a line of code that would fix this problem in my last push to the branch. However, this bug doesn't appear to be happening consistently. While working with the OBSSR documents I noticed a similar sentence (it was a single sentence that was bracketed), where the right bracket was included with the next sentence. 

Strangely, this doesn't just leave the a single bracket in each sentence, but actually throws an exception in pyparsing.

**Comment by thoppe** [comment]
Can you provide a MWE (minimal working example) of the text that throws in error in pyparsing?

**Comment by HarryBaker** [comment]
It is in the mixed_types_unbalanced_test function of remove_parenthesis_test.py in my last push to parens_sentence_bug.

If you uncomment the try/except code from lines 75 to 78 in remove_parenthesis.py, it won't fail on this test. So far every test I've found that triggers the except statement is a bug that should be fixed, rather than being expected behavior. It seems like we should include it in production to prevent crashes, but that would reduce coverage.
