### ISSUE TITLE
token_replacement.py Remove Possessive splits

### ISSUE THREAD

**Issue by HarryBaker** [NIHOPA/NLPre#5]
This is the code to remove possessive splits:

```
# Remove possesive splits
doc = doc.replace(" 's ", ' ')
```

This will only replace the possessive 's if there is a space before it, which I don't think would ever happen.

**Comment by thoppe** [comment]
Double check this and add a unit test. If it's not a problem, you can close it.

**Comment by HarryBaker** [comment]
not an issue
