### ISSUE TITLE
Global logging options

### ISSUE THREAD

**Issue by thoppe** [NIHOPA/NLPre#53]
Is it possible to have the logging options to be set globally? As far as I can tell, setting,

     logging.basicConfig(level=logging.ERROR)

should silence the logger but it currently does not. We should probably make the default logging not so verbose as well.

**Comment by HarryBaker** [comment]
I believe that you set the logging level individually for each file in the logging config. What do you mean by verbose?

**Comment by thoppe** [comment]
I moved away from the global logging configuration file. Logging can now be set by:

```
import nlpre, logging
nlpre.logger.setLevel(logging.INFO)
```

It can also be set per module by calling `nlpre.modulename` via `logging.getLogger`. Docs have been updated to reflect this.
