### ISSUE TITLE
Log Warning When Module Fails

### ISSUE THREAD

**Issue by HarryBaker** [NIHOPA/NLPre#56]
We should have a logger catch when a module fails. My idea is to wrap every module in a try/except statement, unless there's a more elegant way to do it.

The only issue is that this will reduce coverage, unless we can create failing tests for every module. I'm not sure if I can create tests for every module that will cause them to fail. If I found a bug, I'd just fix it. However, it seems important to have a try/except statement to catch errors that we haven't accounted for.

**Comment by thoppe** [comment]
Wrapping every module in a try/except clause is gross. We don't need to do this, as any failures not accounted for will leave tracebacks (thus prompting an error message and hopefully an issue to fix). Also the user can always wrap the calls around a try/except clause if they want to be "safe".

**Comment by thoppe** [comment]
@HarryBaker I'm open to talk about this more tomorrow, I'm working on this now at 10,000 feet flying back home.
