### ISSUE TITLE
Problem with Pattern Parsing Token Sentances

### ISSUE THREAD

**Issue by HarryBaker** [NIHOPA/NLPre#8]
A minor problem I've noticed when using pattern to parse sentences of tokens. When I used tokens as
representations of words (ie, "A B C (D E) F. G"), the token sentences weren't being properly split on periods. "F." is being treated as either an abbreviation or a match in the code block below.  I'm not sure if we will ever encounter this in production, but it's worth noting

    if t.endswith("."):
        if t in abbreviations or \
            RE_ABBR1.match(t) is not None or \
            RE_ABBR2.match(t) is not None or \
            RE_ABBR3.match(t) is not None:

**Comment by thoppe** [comment]
I forgot about that. Replace `ABCD...` with real words, but still require
that output order.

**Comment by HarryBaker** [comment]
So this is expected behavior? Should I close the issue then?

**Comment by thoppe** [comment]
I think it's OK for now. We can revisit this later.
