### ISSUE TITLE
Migrate to python 3

### ISSUE THREAD

**Issue by thoppe** [NIHOPA/NLPre#93]
Pattern is the only thing keeping this library from being 3+ compatible.

https://github.com/clips/pattern
https://spacy.io/

**Comment by thoppe** [comment]
At the moment, spacy.io takes too long to load up. It looks like pattern is moving towards python 3.0 so I'm going to hold off here.

**Comment by facepalm** [comment]
Pattern builds from source in 3 now, with the extra hiccup of a mysql dependency.

**Comment by thoppe** [comment]
@facepalm from the site

> Pattern supports Python 2.7 and Python 3.6+. The Python 3 version is currently only available on the development branch. 

From this [SO answer](https://stackoverflow.com/a/33451105/249341), it looks like I can have `requirements.txt` have specific versions tagged with them, so perhaps this is possible.
