### ISSUE TITLE
Garbage texts

### ISSUE THREAD

**Issue by HarryBaker** [NIHOPA/NLPre#94]
Sometimes there are corrupted texts on iSearch, where every word in the document is corrupted. See Appl ID 7889277 for an example. I think this can be pretty easily solved by checking every word in a document against a dictionary, and if a certain percentage aren't listed you can assume the text is corrupted.

**Comment by thoppe** [comment]
This isn't a bug fix or direct improvement (possibly an outside tool). Closing.
